CREATE DATABASE IF NOT EXISTS sistema_clientes;
USE sistema_clientes;

CREATE TABLE IF NOT EXISTS clientes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    telefone VARCHAR(20) NOT NULL,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE clientes
ADD COLUMN cpf VARCHAR(14) NOT NULL UNIQUE AFTER email,
ADD COLUMN cep VARCHAR(9) NOT NULL AFTER telefone,
ADD COLUMN logradouro VARCHAR(100) NOT NULL AFTER cpf,
ADD COLUMN bairro VARCHAR(50) NOT NULL AFTER logradouro,
ADD COLUMN cidade VARCHAR(50) NOT NULL AFTER bairro,
ADD COLUMN estado VARCHAR(50) NOT NULL AFTER cidade,
ADD COLUMN cnpj VARCHAR(14) NULL UNIQUE AFTER cpf
